module Locations where
import Engine
import Items
import StandardOptions

locations :: [Location]
locations = [
  Location {name = "Start",
            description = "Hello, Brad Miller.\n\nYour friend David is not responding to your emails.  You want to do something dramatic to get his attention.  You have decided to Dig a Tunnel to The Center of the Moon!\n\n\"But I can't dig a tunnel to the center of the moon!\"  You say.\n\nBut we have faith in you, Brad.  You just need a plan.  Step 1. Get to the moon!  Will you buy a rocket ship, build a rocket ship, make a friend who has a rocket ship, use an African swallow, use a European swallow, or use a trebuchet?",
            items = [],
            options = [("buy", "buy"),
                       ("build", "build"),
                       ("friend", "friend"),
                       ("African swallow", "swallow"),
                       ("European swallow", "Euroswallow"),
                       ("trebuchet", "trebuchet")],
            otherOptions = standardOptions},
  Location {name = "buy",
            description = "You have decided to buy a rocket ship, wise choice.  Problem is you don't have much cash.  You could always buy a cheep one on Craigslist, look for a Russian one on the black market, or work on getting a nicer model by robbing a bank.",
            items = [],
            options = [("craigslist", "craigslist"),
                       ("Russian", "Russian"),
                       ("bank", "bank")],
            otherOptions = standardOptions},
  Location {name = "craigslist",
            description = "They've got everything on Craigslist right?  Specifically they have a Ford F-150 with a rocket strapped to it for some reason, a human sized hamster wheel, and some guy with \"magic beans\".",
            items = [],
            options = [("truck", "truck"),
                       ("wheel", "wheel"),
                       ("beans", "beans")],
            otherOptions = standardOptions},
  Location {name = "truck",
            description = "Ok!  You've got a plan for step 1: getting to the moon.  Now on to step 2: digging a tunnel.  Do you want to dig this tunnel or use explosives?",
            items = [],
            options = [("dig", "tunnel"),
                       ("explosives", "explosives")],
            otherOptions = standardOptions},
  Location {name = "tunnel",
            description = "Well, you're going to need a shovel.  You call around and it turns Casey has a camping shovel you can borrow.  He says you can stop by the bar and pick it up.  Or if you're in a hurry you could always just bring a spoon from the kitchen drawer.",
            items = [],
            options = [("shovel", "shovel"),
                       ("spoon", "spoon")],
            otherOptions = standardOptions},
  Location {name = "shovel",
            description = "You go meet Casey at work.  \"Hey Brad!  Glad you stopped by, have a drink!\"  You and Casey both have a drink...\nThen another drink...\n\nAnd another drink...\n\nUntil suddenly it's really late and you're kinda drunk and you decide to call it a night and go home.  And really who wants to dig a tunnel to the center of the moon anyway, that sounds like kind of a lot of work.  Whatever.\n\nThe End.",
            items = [],
            options = [],
            otherOptions = standardOptions},
  Location {name = "spoon",
            description = "You grab a spoon and hop in the truck.  You figure you need to get going in the right direction so you drive to the base of a hill, start heading up and fire up the rocket.  Unfortunately the rocket doesn't work.  So you're just at the top of the mountain hanging out with a truck with a dead rocket strapped to it.  Lame!\n\nYou contemplate your options.  You could call the dude from Craigslist and ask why the rocket doesn't work.  Or you could drive home in shame and try to get rid of the truck before you have to explain to Jenny why you own a truck with a rocket on it.",
            items = [],
            options = [("call", "call"),
                       ("shame", "shame")],
            otherOptions = standardOptions},
  Location {name = "call",
            description = "\"Hello, Mr. Jones.  I'm afraid the rocket you sold me isn't working.\"\n\n\"What the fuck are you talking about?  That rocket is fine!\"\n\n\"Well I started at the base of a hill and started driving up and then I fired up the rocket and nothing happened\"\n\n\"What kind of fucking idiot are you? Rockets don't work on hills!\"\n\n\"But, sir.  I need it to work on a hill...\"\n\n\"Fuck you and your fucking hill.  If you wanna talk shit about my rocket you can come here and do it to my face!\"\n\n... of course there's also always the option of trying it out on flat ground",
            items = [],
            options = [("face", "face"),
                       ("flat", "flat")],
            otherOptions = standardOptions},
  Location {name = "face",
            description = "You drive the truck over to Mr. Jones' place to show him that the rocket isn't working.  You're right, it's not working.  Unfortunately Mr. Jones doesn't do returns.  He just gets very angry and chases you away with a shotgun.   You make it out alive, but you're unfortunately down a truck.   You're in the middle of nowhere with nothing but a spoon.\n\nAs you wander you come across a phone booth.  Do you pick up the phone booth (up) or call (call) Jenny and ask her to pick you up?",
            items = [],
            options = [("up", "up"),
                       ("call", "call")],
            otherOptions = standardOptions},
  Location {name = "up",
            description = "As you attempt to pick up the phone booth it falls killing you.  A toast to your memory!  Everyone drink!\n\nThe end.",
            items = [],
            options = [],
            otherOptions = standardOptions},
  Location {name = "call",
            description = "You call Jenny, but she's in delivery right now and can't answer her phone.  So you wait around a while until she can pick you up.  At least the phone booth is pretty comfy.  You might as well pass the time, by finishing your drink.\n\nThe end.",
            items = [],
            options = [],
            otherOptions = standardOptions},
  Location {name = "flat",
            description = "Well Mr. Jones is clearly the expert in trucks with rockets strapped to them.  So you find a nice long flat stretch of road and take off at high speeds.  You fire the rocket up and lo and behold it works.  You hurtle faster and faster down the road.  But alas, even the longest and flattest stretch of road is not long and flat forever.  Ahead of you is a cliff and while you try to make the turn around it, the momentum of the rocket is too much and you smash into the cliff face.\n\nWe drink in your memory.  A toast! \"To Brad!\"\n\nThe end.",
            items = [],
            options = [],
            otherOptions = standardOptions},
  Location {name = "shame",
            description = "You drive the stupid useless \"rocket truck\" home.  You better come up with some way to get rid of this thing.  You could relist it on Craigslist or disassemble it and try to build a better rocket ship.",
            items = [],
            options = [("relist", "relist"),
                       ("disassemble", "better")],
            otherOptions = standardOptions},
  Location {name = "relist",
            description = "You repost a listing on Craigslist.\n\n\"Super cool Ford F-150 with a rocket on top!  Goes hella fast.  Doesn't work on hills.  Best offer\"\n\nThen you wait, while you wait you drink.  But before too long you get a call.  It's Jason.\n\n\"I like the awesome truck with the rocket on top.\"\n\n\"Jason is that you?\"\n\n\"Brad?\"\n\n\"Yeah!\"\n\n\"What are you doing with a truck with a rocket on it?\"\n\n\"I was trying to dig a tunnel to the center of the moon\"\n\n\"Why would you want to dig a tunnel to center of the moon?\"\n\n\"I'm trying to get my friend's attention\"\n\n\"Nah, man moon tunnels are awesome!  I get that.  I mean why do you want to DIG a tunnel?\"\n\n\"How else do you get a tunnel on the moon?\"\n\n\"With a laser, duh!\"\n\nYou agree to give Jason the rocket truck if he helps you burn a tunnel to the center of the moon with a giant laser.  Once you have completed your tunnel the two of you go drink to celebrate a job well done.\n\nDavid notices your moon tunnel and calls you to ask what's up.  You tell him to drink too.\n\nThe End.",
            items = [],
            options = [],
            otherOptions = standardOptions},
  Location {name = "better",
            description = "You begin to deconstruct the rocket truck.  You get the sense that you really know what was going on here and why it didn't work.  You are convinced you can do it better.  You start searching for diagrams on the internet.  You need more parts and you go and find them.  Two years later you are still perfecting your rocket truck.  The rest of us are drinking while we wait for you.\n\nThe End.",
            items = [],
            options = [],
            otherOptions = standardOptions},
  Location {name = "explosives",
            description = "NOTDONE!!!",
            items = [],
            options = [("tunnel", "tunnel"),
                       ("explosives", "explosives")],
            otherOptions = standardOptions},
  Location {name = "wheel",
            description = "Ok!  You've got a plan for step 1: getting to the moon.  Now on to step 2: digging a tunnel.  Do you want to dig this tunnel or use explosives?",
            items = [],
            options = [("tunnel", "tunnel"),
                       ("explosives", "explosives")],
            otherOptions = standardOptions},
  Location {name = "kitchen",
            description = "NOTDONE!!!",
            items = [],
            options = [("craigslist", "craigslist"),
                       ("Russian", "Russian"),
                       ("bank", "bank")],
            otherOptions = standardOptions},
  Location {name = "snack",
            description = "NOTDONE!!!",
            items = [],
            options = [("craigslist", "craigslist"),
                       ("Russian", "Russian"),
                       ("bank", "bank")],
            otherOptions = standardOptions},
  Location {name = "Russian",
            description = "NOTDONE!!!",
            items = [],
            options = [("craigslist", "craigslist"),
                       ("Russian", "Russian"),
                       ("bank", "bank")],
            otherOptions = standardOptions},
  Location {name = "milk",
            description = "NOTDONE!!!",
            items = [],
            options = [("craigslist", "craigslist"),
                       ("Russian", "Russian"),
                       ("bank", "bank")],
            otherOptions = standardOptions},
  Location {name = "bank",
            description = "NOTDONE",
            items = [],
            options = [("craigslist", "craigslist"),
                       ("Russian", "Russian"),
                       ("bank", "bank")],
            otherOptions = standardOptions},
  Location {name = "Euroswallow",
            description = "You cannot find a swallow, African or European.  Not that a European swallow would have managed it anyway, of course.  It's a simple question of weight ratios.  A five-ounce bird could never carry a 1-pound coconut, let alone you.  In order to maintain airspeed velocity a swallow needs to beat its wings 43 times a second, right?...\n\n...OK, OK, you can, however, find a parrot.  On the shoulder of a pirate, who's about 10 feet in front of you.  At least you assume he's a pirate, because he also has a peg leg.  He doesn't see you.",
            items = [],
            options = [("sneak", "swallow 2")],
            otherOptions = standardOptions},
  Location {name = "swallow",
            description = "Good call.  A European swallow wouldn't have managed it.  It's a simple question of weight ratios.  A five-ounce bird could never carry a 1-pound coconut, let alone you.  An African swallow could carry you though, but of course they're non-migratory so they wouldn't take you to the moon.\n\nIn any case, you cannot find a swallow, African or European.  But you CAN find a parrot.  On the shoulder of a pirate, who's about 10 feet in front of you.  At least you assume he's a pirate, because he also has a peg leg.  He doesn't see you.",
            items = [],
            options = [("sneak", "swallow 2")],
            otherOptions = standardOptions},
  Location {name = "swallow 2",
            description = "There is a pirate about 5 feet in front of you.  He doesn't see you.",
            items = [],
            options = [("sneak", "swallow 3")],
            otherOptions = standardOptions},
  Location {name = "swallow 3",
            description = "There is a pirate right in front of you.  He doesn't see you.",
            items = [],
            options = [("ninja", "swallow 4")],
            otherOptions = standardOptions},
  Location {name = "swallow 4",
            description = "Well, it turns out the pirate also had booze, which seems to make the \"swallow\" plan feasible after all.  So once you get to the moon, how are you going to tunnel to the center? WE NEED SOME STUPID OPTIONS HERE!!!!",
            items = [Booze, Parrot, ExPirate],
            options = [],
            otherOptions = standardOptions},
  Location {name = "the end",
            description = "The End",
            items = [],
            options = [],
            otherOptions = standardOptions}]